import Head from 'next/head'
import * as S from './style'
import BubbleSort from '@/components/BubbleSort'

import { Roboto } from 'next/font/google';

const robotoScript = Roboto({ subsets: ['latin'], weight: ["300","400", "500", "700"], display: 'swap'});


export default function Home() {
    

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container style={robotoScript.style}>
        <BubbleSort/>
      </S.Container>
    </>
  )
}
